/**
 * Created by 94712 on 2017/8/30.
 */
angular.module('login',[])
.directive('nglLogin',[function(){
        return{
            scope:{},
            restrict:'E',
            templateUrl:'/src/components/common/login/login.html',
            replace:true,
            controller:'nglLoginCtrl'
        }
    }])
    .controller('nglLoginCtrl',['$scope','$location','$http',function($scope,$location,$http){
            $scope.user={
                tc_name:'',
                tc_pass:''
            }
        $scope.login=function(){
            $http({
                url:'/api/login',
                method:'post',
                data:'tc_name='+$scope.user.tc_name+'&'+'tc_pass='+$scope.user.tc_pass,
                headers:{
                    'Content-Type':'application/x-www-form-urlencoded'
                }
            })
                .then(function(resp){
                    console.log(resp);
                    var data=resp.data;
                    if(data.code==200){
                        localStorage.setItem('userInfo',JSON.stringify(data.result));
                        $location.path('/');
                    }
                    else{
                        alert('服务器响应错误')
                    }
                })
        }

    }])