/**
 * Created by 94712 on 2017/8/31.
 */
angular.module('web_api',[])
.constant('WEB_API',{
        //登录
        login:{
            url:'/api/login',
            method:'get'
        },
        //退出
        logout:{
            url:'/api/logout',
            method:'post'
        },
        //修改密码
        repass:{
            url:'/api/teacher/repass',
            method:'post'
        }
    })